version: "3.8"

services:
  minicloud_web_admin_v3:
    build: ./minicloud_web_admin_v3
    env_file: "./minicloud_web_admin_v3/.env"
    ports:
      - "3000:80"

  minicloud_web_client_v3:
    build: ./minicloud_web_client_v3
    env_file: "./minicloud_web_client_v3/.env"
    ports:
      - "80:80"
