version: "3.8"

services:
  backend:
    build: ./minicloud_web_admin_v3
    env_file: "./minicloud_web_admin_v3/.env"
    ports:
      - "80:3000"

  frontend:
    build: ./minicloud_web_client_v3
    env_file: "./minicloud_web_client_v3/.env"
    ports:
      - "80:80"
