version: "3.8"

services:
  admin:
    build: ./minicloud_web_admin_v3
    env_file: "./minicloud_web_admin_v3/.env"
    ports:
      - "3000:80"

  client:
    build: ./minicloud_web_client_v3
    env_file: "./minicloud_web_client_v3/.env"
    ports:
      - "80:80"
